---
build_targets:
    linux32: Linux_x86-gcc3
    linux64: Linux_x86_64-gcc3
    win32: WINNT_x86-gcc3
    osx32: Darwin_x86-gcc3
channels:
    release: 4.0.1
    alpha: 4.0.1
versions:
    4.0:
        platformVersion: 31.2.0
        detailsURL: https://www.torproject.org/projects/torbrowser.html.en
        download_url: https://www.torproject.org/dist/torbrowser/4.0
    4.0.1:
        platformVersion: 31.2.0
        detailsURL: https://www.torproject.org/projects/torbrowser.html.en
        download_url: https://www.torproject.org/dist/torbrowser/4.0.1
        incremental_from:
            - 4.0
#       osx32:
#          minSupportedOSVersion: 10.7
#          unsupported: 1
